version: "3"

services:
  # https://hub.docker.com/_/postgres/
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    # <host_port>:<container_port>
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -p 5432 -U ${POSTGRES_USER} ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 10s
      retries: 5

  # https://hub.docker.com/r/dpage/pgadmin4
  pgadmin:
    image: dpage/pgadmin4:6
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
        - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
    postgres_data:
    pgadmin_data:
