[project]
  name = "rdb_spotify_tags_etl_py"
  timezone = "America/Los_Angeles"
  sources = ["json.spotify.api", "json.media.parser"]
  sinks = ["postgres.db"]

# postgres port: 5432 (default), 5454 (custom)
[postgres.dev]
  endpoint = "localhost"
  username = "some_user"
  password = "some_password"
  database = "media_db"
  port = 5454
  timeout = 5

# https://developer.spotify.com/documentation/web-api/
[spotify.dev]
  client_id = "123456789abcdefg"        # <-- enter your CLIENT_ID
  client_secret = "abcdefg123456789"    # <-- enter your CLIENT_SECRET
  redirect_uri = "http://localhost"
  port = 9000
  scopes = [
    "user-library-read",
    "user-library-modify",
    "user-read-recently-played",
    "playlist-read-private",
  ]
  market = "US"
  # prevent hitting quota limits
  api_timeout = 0.5
  # maximum number of items returned in response for spotify is 50
  api_limit = 50
  # confidence threshold
  thold = 70.0
